tsesh fzf improvements (tmux popup window)

diff --git a/custom_bins/tsesh b/custom_bins/tsesh
--- a/custom_bins/tsesh
+++ b/custom_bins/tsesh
@@ -1,28 +1,80 @@
 #!/bin/bash
 
+USAGE=$(cat <<-END
+Usage: tsesh <PATH>
+
+Tmux session switcher, if a PATH argument is provided will either switch to or 
+start a new session named after the basename of that path and in that location.
+If no PATH is provided a fzf window will be presented from common options.
+
+OPTIONS:
+    --popup [use if called from a tmux popup window, changes some fzf options]
+END
+)
+POSITIONAL_ARGS=()
+while (( "$#" )); do
+    case "$1" in
+        -h|--help)
+            echo "$USAGE" && exit 1 ;;
+        --popup)
+            POPUP=true && shift ;;
+        --) # end argument parsing
+            shift && break ;;
+        -*|--*=) # unsupported flags
+            echo "Error: Unsupported flag $1" >&2 && exit 1 ;;
+        *)
+            POSITIONAL_ARGS+=("$1") # save positional arg
+            shift ;;
+    esac
+done
+
+set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
+
 
 # Selection using fzf ---
+transform_name(){
+   name="$1"
+   sesh_name=$(basename "$name")
+    if [[ $name == "/exp/$(whoami)" ]] ; then
+        sesh_name="exp"
+    elif [[ $name == *"/git/aladdin/"* ]] ; then
+        sesh_name="aladdin-$sesh_name"
+    fi
+    echo "$sesh_name"
+}
 
-possible_options="$HOME/git"
-possible_options+=" $HOME/git/aladdin"
-if [ -d "/perish_aml02" ]; then
-    possible_options+=" /perish_aml02/edwardr/git"
-fi
-exact=" /exp/$(whoami)"
-exact2=" $HOME/tb"
+make_nice() {
+    echo "Session Directory Status"  #Headings
+    while IFS=$'\n' read -r line; do
+        name="$(transform_name $line)"
+        if tmux has-session -t="$name" 2> /dev/null ; then
+            status="running"
+        else
+            status="create?"
+        fi
+        echo "$name $line $status"
+    done | sort -r -k3,3 -k1,1
+}
 
+find_directories(){
+    echo "/exp/$(whoami)"
+    echo "$HOME/tb"
+    possible_options="$HOME/git"
+    possible_options+=" $HOME/git/aladdin"
+    find  $possible_options -mindepth 1 -maxdepth 1 -type d -not -path '*/.*';
+}
+fzf_args="--header-lines=1"
 if [[ $# -eq 1 ]]; then
     selected=$1
 else
-    selected=$({ echo $exact; echo $exact2; find $possible_options -mindepth 1 -maxdepth 1 -type d; } | fzf)
+    if [ ! -z $POPUP ]; then
+        fzf_args+=" --border=none --height=100%"
+    fi
+    selected=$(find_directories | make_nice | column -t -s' '| sed '1s/^/  /' | fzf $fzf_args )
+    selected=$(echo $selected | awk '{ print $2 }')
 fi
 
-sesh_name=$(basename "$selected" | tr . _)
-if [[ $selected == "/exp/$(whoami)" ]] ; then
-    sesh_name="exp"
-elif [[ $selected == *"/git/aladdin/"* ]] ; then
-    sesh_name="aladdin-$sesh_name"
-fi
+sesh_name=$(transform_name $selected)
 
 if [[ -z $selected ]]; then
     exit 0
@@ -33,9 +85,9 @@ fi
 # accept tsesh default
 if [[ $sesh_name == "default" ]]; then
     was_default=true
-    if [[ $LOC == "remote " ]]; then
-        sesh_name="aladdin-feature"
-        selected="$HOME/git/aladdin/feature"
+    if [[ $LOC == "remote" ]]; then
+        sesh_name="aladdin-WIP_feature"
+        selected="$HOME/git/aladdin/WIP_feature"
         args="make shell 2> /dev/null"
     else
         sesh_name="local"
@@ -63,6 +115,7 @@ if [[ -z $TMUX ]] && [[ -z $is_running ]]; then
 fi
 
 # If tmux is running but does not have a session with that name
+# create new session but dont attach
 if ! tmux has-session -t=$sesh_name 2> /dev/null; then
     tmux new-session -ds $sesh_name -c $selected $args
 fi
